openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0
servers:
  - url: http://localhost:4010
paths:
  /users:
    get:
      summary: Get all users
      responses:
        '200':
          description: A list of users.
          content:
            application/json:
              example:
                - id: 1
                  name: 'John Doe'
                - id: 2
                  name: 'Jane Smith'